services:
  mongodb:
    image: mongodb/mongodb-community-server:8.0-ubi8
    container_name: mongo_ejercicios
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ejercicios

volumes:
  mongo_data: